### ISSUE TITLE
Could you make a version to scan novel in booklivejp please?

### ISSUE THREAD

**Issue by DavidWilliam11** [Flareonz44/booklive-jp-manga-dumper#1]

**Comment by Flareonz44** [comment]
I made some scripts to test if it's possible to add the feature you requested, however I found a huge problem: if the novel is purely jp characters, that's ok and pages could be dumped successfully, but if the page contains images such as pictures or special characters (like ' !!! '), that will taint the canvas, making it impossible to dump due to security restrictions that I can't bypass that easily :/

![image](https://github.com/user-attachments/assets/39a0c552-b17c-4aab-a0c0-f337cecdd7bd)

I’m investigating, though, to find a bypass for this

**Comment by Flareonz44** [comment]
@DavidWilliam11 I just updated the script to support novel scanning. Thanks for the idea!
